/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormularioKardex;

import BD.BD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jluis
 */
public class ConsultaKardex extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaKardex
     */
    public ConsultaKardex() {
        initComponents();
    }

    
    public void obtenerdescripcion() {

        try {
            Connection con = BD.getConnection();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select producto.descripcion,UNIDAD_MEDIDA.DESCRIPCION as \"descmedida\" from producto inner join UNIDAD_MEDIDA on producto.id_medida = UNIDAD_MEDIDA.ID_MEDIDA where codigo=" + codigo.getText());
            rs.next();
            descripcion.setText(rs.getString("descripcion"));
            medida.setText(rs.getString("descmedida"));
            codigostrin.setText(codigo.getText());
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR CONTACTE AL ADMINISTRADOR DEL SISTEMA" + e);
        }
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Karde = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        descripcion = new javax.swing.JTextField();
        codigostrin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        medida = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Karde1 = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        Karde.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TIPO", "FECHA", "CANTIDAD INGRESO", "PRECIO INGRESO", "TOTAL INGRESO", "CANTIDAD DESCARGA", "VALOR DESCARGA", "TOTAL DESCARGA", "CANTIDAD SALDO", "PRECIO SALDO", "TOTAL SALDO"
            }
        ));
        jScrollPane1.setViewportView(Karde);

        jLabel1.setText("CODIGO");

        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        descripcion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        descripcion.setForeground(new java.awt.Color(255, 0, 0));

        codigostrin.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        codigostrin.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("DESCRIPCION");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CODIGO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("UNIDAD DE MEDIDA");

        medida.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        medida.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(medida, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(codigostrin)
                    .addComponent(descripcion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigostrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Karde1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TIPO", "FECHA", "CANTIDAD INGRESO", "PRECIO INGRESO", "TOTAL INGRESO", "CANTIDAD DESCARGA", "VALOR DESCARGA", "TOTAL DESCARGA", "CANTIDAD SALDO", "PRECIO SALDO", "TOTAL SALDO"
            }
        ));
        jScrollPane2.setViewportView(Karde1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscar))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1225, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

          actualizarTablaconsulta();
          actualizarTablaconsulta2();
          obtenerdescripcion();

    }//GEN-LAST:event_buscarActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        buscar.requestFocus();
    }//GEN-LAST:event_codigoActionPerformed

    private void actualizarTablaconsulta() {

        ArrayList<ClassKardex> result = BDKardex.ListarProductoIngresado(Integer.parseInt(codigo.getText()));
        recagarTabla(result);
    }

    private void recagarTabla(ArrayList<ClassKardex> list) {

        Object[][] dato = new Object[list.size()][11];
        int f = 0;
        for (ClassKardex a : list) {
            dato[f][0] = a.getTipo();
            dato[f][1] = a.getFecha();
            dato[f][2] = a.getCantidadin();
            dato[f][3] = a.getPrecioin();
            dato[f][4] = a.getTotalin();
            dato[f][5] = a.getCantidadout();
            dato[f][6] = a.getPrecioout();
            dato[f][7] = a.getTotalout();
            dato[f][8] = a.getCantidadsaldo();
            dato[f][9] = a.getPreciosaldo();
            dato[f][10] = a.getTotalsaldo();
            f++;
        }
        Karde.setModel(new javax.swing.table.DefaultTableModel(
                dato,
                new String[]{
                    "TIPO","FECHA","CANTIDAD INGRESO","PRECIO INGRESO","TOTAL INGRESO","CANTIDAD DESCARGA","PRECIO DESCARGA","TOTAL DESCARGA","CANTIDAD SALDO","PRECIO SALDO","TOTAL SALDO"
                }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }
    
    
    private void actualizarTablaconsulta2() {

        ArrayList<ClassKardex> result = BDKardex.ListarProductoIngresado2(Integer.parseInt(codigo.getText()));
        recagarTabla2(result);
    }

    private void recagarTabla2(ArrayList<ClassKardex> list) {

        Object[][] dato = new Object[list.size()][11];
        int f = 0;
        for (ClassKardex a : list) {
            dato[f][0] = a.getTipo();
            dato[f][1] = a.getFecha();
            dato[f][2] = a.getCantidadin();
            dato[f][3] = a.getPrecioin();
            dato[f][4] = a.getTotalin();
            dato[f][5] = a.getCantidadout();
            dato[f][6] = a.getPrecioout();
            dato[f][7] = a.getTotalout();
            dato[f][8] = a.getCantidadsaldo();
            dato[f][9] = a.getPreciosaldo();
            dato[f][10] = a.getTotalsaldo();
            f++;
        }
        Karde1.setModel(new javax.swing.table.DefaultTableModel(
                dato,
                new String[]{
                    "TIPO","FECHA","CANTIDAD INGRESO","PRECIO INGRESO","TOTAL INGRESO","CANTIDAD DESCARGA","PRECIO DESCARGA","TOTAL DESCARGA","CANTIDAD SALDO","PRECIO SALDO","TOTAL SALDO"
                }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Karde;
    private javax.swing.JTable Karde1;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField codigostrin;
    private javax.swing.JTextField descripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField medida;
    // End of variables declaration//GEN-END:variables
}
