/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BD.BD;
import TrabajosFormularios.*;
import java.awt.Dimension;
import javax.swing.JFrame;
import Consultas.*;
import FormularioKardex.ConsultaKardex;
import P.UpdateCantidadMinima;
import Reportes.ReporteBodega;
import Reportes.ReporteCostos;
import Reportes.ReportesDetalladosMES;
import ReportesKardex2.ReportesDetalladosKardex2;
//import com.sun.org.apache.bcel.internal.generic.CPInstruction;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge Luis
 */
public class PrincipalInventario extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalInventario
     */
    public PrincipalInventario() {
      Color b=new Color(0,150,255);
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        menubar.setForeground(Color.GREEN);
        avencer();
        
       /* Agotados M = new Agotados();
                jDesktopPane1.add(M);
                Dimension desktopSize = jDesktopPane1.getSize();
                Dimension FrameSize = M.getSize();
                M.setLocation((850), (325));
                M.show();*/
           
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mProcedencia1 = new Formularios.MProcedencia();
        mProcedencia2 = new Formularios.MProcedencia();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        NUEVOPRO = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        CARGAPRO = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        CARGAPRO1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu13 = new javax.swing.JMenu();
        EDITARPRO = new javax.swing.JMenuItem();
        INGRESO = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        familias = new javax.swing.JMenuItem();
        unidadmedida = new javax.swing.JMenuItem();
        presentacion = new javax.swing.JMenuItem();
        PROCEDENCIA = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        DESCARGAPRO = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        CONSULTAPN = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        Vencimientos = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        DWN = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE INVENTARIO DE BODEGA");
        setLocation(new java.awt.Point(0, 0));
        setMaximizedBounds(getMaximizedBounds());

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jInternalFrame1.setVisible(false);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText(" ELETTRONICI, S.A.");

        jDesktopPane1.setLayer(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(808, 808, 808)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        menubar.setBorder(null);
        menubar.setBorderPainted(false);
        menubar.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        menubar.setPreferredSize(new java.awt.Dimension(109, 40));
        menubar.setRequestFocusEnabled(false);

        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(0, 51, 255));
        jMenu1.setText("  INGRESOS");
        jMenu1.setActionCommand("   INGRESOS");
        jMenu1.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 30));
        jMenu1.setRequestFocusEnabled(false);
        jMenu1.setVerifyInputWhenFocusTarget(false);

        jMenu7.setForeground(new java.awt.Color(0, 51, 255));
        jMenu7.setText("PRODUCTOS");
        jMenu7.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(139, 35));

        NUEVOPRO.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        NUEVOPRO.setForeground(new java.awt.Color(0, 51, 255));
        NUEVOPRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/New.png"))); // NOI18N
        NUEVOPRO.setText("NUEVO PRODUCTOS");
        NUEVOPRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVOPROActionPerformed(evt);
            }
        });
        jMenu7.add(NUEVOPRO);
        jMenu7.add(jSeparator1);

        CARGAPRO.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        CARGAPRO.setForeground(new java.awt.Color(0, 51, 255));
        CARGAPRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Next.png"))); // NOI18N
        CARGAPRO.setText("CARGAR PRODUCTOS");
        CARGAPRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARGAPROActionPerformed(evt);
            }
        });
        jMenu7.add(CARGAPRO);
        jMenu7.add(jSeparator2);

        CARGAPRO1.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        CARGAPRO1.setForeground(new java.awt.Color(0, 51, 255));
        CARGAPRO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Next.png"))); // NOI18N
        CARGAPRO1.setText("CARGAR PRODUCTOS CONTABLES");
        CARGAPRO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARGAPRO1ActionPerformed(evt);
            }
        });
        jMenu7.add(CARGAPRO1);
        jMenu7.add(jSeparator3);

        jMenu13.setForeground(new java.awt.Color(0, 51, 255));
        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit2.png"))); // NOI18N
        jMenu13.setText("EDITAR");
        jMenu13.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N

        EDITARPRO.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        EDITARPRO.setForeground(new java.awt.Color(0, 51, 255));
        EDITARPRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit2.png"))); // NOI18N
        EDITARPRO.setText("PRODUCTO");
        EDITARPRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITARPROActionPerformed(evt);
            }
        });
        jMenu13.add(EDITARPRO);

        INGRESO.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        INGRESO.setForeground(new java.awt.Color(0, 51, 255));
        INGRESO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit2.png"))); // NOI18N
        INGRESO.setText("INGRESO");
        INGRESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESOActionPerformed(evt);
            }
        });
        jMenu13.add(INGRESO);

        jMenu7.add(jMenu13);

        jMenu1.add(jMenu7);

        jMenu6.setForeground(new java.awt.Color(0, 51, 255));
        jMenu6.setText("COMPONENTES DE PRODUCTO");
        jMenu6.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(271, 35));

        familias.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        familias.setForeground(new java.awt.Color(0, 51, 255));
        familias.setText("FAMILIAS");
        familias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familiasActionPerformed(evt);
            }
        });
        jMenu6.add(familias);

        unidadmedida.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        unidadmedida.setForeground(new java.awt.Color(0, 51, 255));
        unidadmedida.setText("UNIDAD DE MEDIDA");
        unidadmedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadmedidaActionPerformed(evt);
            }
        });
        jMenu6.add(unidadmedida);

        presentacion.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        presentacion.setForeground(new java.awt.Color(0, 51, 255));
        presentacion.setText("PRESENTACION");
        presentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentacionActionPerformed(evt);
            }
        });
        jMenu6.add(presentacion);

        PROCEDENCIA.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        PROCEDENCIA.setForeground(new java.awt.Color(0, 51, 255));
        PROCEDENCIA.setText("PROCEDENCIA");
        PROCEDENCIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROCEDENCIAActionPerformed(evt);
            }
        });
        jMenu6.add(PROCEDENCIA);

        jMenu1.add(jMenu6);

        jMenuItem40.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem40.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem40.setText("EDITAR CANTIDAD MINIMA");
        jMenuItem40.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem40);

        menubar.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(0, 51, 255));
        jMenu3.setText("  DESCARGAS");
        jMenu3.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(110, 19));

        DESCARGAPRO.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        DESCARGAPRO.setForeground(new java.awt.Color(0, 51, 255));
        DESCARGAPRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Download.png"))); // NOI18N
        DESCARGAPRO.setText("Descarga de Producto");
        DESCARGAPRO.setPreferredSize(new java.awt.Dimension(197, 35));
        DESCARGAPRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DESCARGAPROActionPerformed(evt);
            }
        });
        jMenu3.add(DESCARGAPRO);

        menubar.add(jMenu3);

        jMenu2.setForeground(new java.awt.Color(0, 51, 255));
        jMenu2.setText("  CONSULTAS");
        jMenu2.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(110, 19));
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenu10.setForeground(new java.awt.Color(0, 51, 255));
        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenu10.setText("PRODUCTOS");
        jMenu10.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N

        jMenuItem24.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem24.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem24.setText("PRODUCTO POR NOMBRE");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem24);

        jMenuItem3.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem3.setText("CODIGO PRODUCTO");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem3);

        jMenuItem10.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem10.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem10.setText("BALANCE DE PRODUCTO");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem10);

        jMenu2.add(jMenu10);

        jMenu8.setForeground(new java.awt.Color(0, 51, 255));
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenu8.setText("INGRESOS");
        jMenu8.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N

        jMenuItem21.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem21.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem21.setText("CODIGO");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem21);

        jMenuItem6.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem6.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem6.setText("CODIGO DETALLE");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem6);

        jMenuItem23.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem23.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem23.setText("POR NOMBRE");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem23);

        jMenuItem17.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem17.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem17.setText("DESCRIPCION");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem17);

        jMenuItem11.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem11.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem11.setText("FECHA ");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenuItem4.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem4.setText("RANGO DE FECHAS");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem4);

        jMenuItem8.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem8.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem8.setText("P/N");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        jMenuItem7.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem7.setText("#INVOICE");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem7);

        jMenuItem1.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem1.setText("P.O.");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem2.setText("JOB");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem2);

        jMenu2.add(jMenu8);

        jMenu9.setForeground(new java.awt.Color(0, 51, 255));
        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenu9.setText("DESCARGAS");
        jMenu9.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem12.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem12.setText("FECHA ");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem12);

        CONSULTAPN.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        CONSULTAPN.setForeground(new java.awt.Color(0, 51, 255));
        CONSULTAPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        CONSULTAPN.setText("P/N");
        CONSULTAPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTAPNActionPerformed(evt);
            }
        });
        jMenu9.add(CONSULTAPN);

        jMenuItem9.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem9.setText("CODIGO");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem9);

        jMenuItem20.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem20.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem20.setText("CODIGO DETALLES");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem20);

        jMenuItem13.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem13.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem13.setText("RANGO DE FECHA");
        jMenuItem13.setHideActionText(true);
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem13);

        jMenuItem16.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem16.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem16.setText("P.O.");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem16);

        jMenuItem39.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem39.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem39.setText("JOB");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem39);

        jMenu2.add(jMenu9);

        Vencimientos.setForeground(new java.awt.Color(0, 51, 255));
        Vencimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        Vencimientos.setText("VENCIMIENTOS");
        Vencimientos.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N

        jMenuItem14.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem14.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem14.setText("MATERIALES VENCIDOS");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        Vencimientos.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem15.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem15.setText("MATERIALES POR VENCER");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        Vencimientos.add(jMenuItem15);

        jMenu2.add(Vencimientos);

        jMenuItem18.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem18.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem18.setText("POR AGOTARSE");
        jMenuItem18.setFocusTraversalPolicyProvider(true);
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        jMenu12.setForeground(new java.awt.Color(0, 51, 255));
        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenu12.setText("REPORTES CONTABILIDAD");
        jMenu12.setToolTipText("");
        jMenu12.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N

        jMenuItem42.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem42.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem42.setText("CONSULTA KARDEX");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem42);

        jMenuItem34.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem34.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem34.setText("REPORTE INVENTARIO KARDEX");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem34);

        jMenuItem38.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem38.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem38.setText("REPORTE INVENTARIO KARDEX DECRETO 2989");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem38);

        jMenuItem31.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem31.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        jMenuItem31.setText("REPORTE CONTABILIDAD");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem31);

        jMenuItem41.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem41.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem41.setText("REPORTE DE COSTO MENSUAL");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem41);

        jMenu2.add(jMenu12);

        menubar.add(jMenu2);

        jMenu4.setForeground(new java.awt.Color(0, 51, 255));
        jMenu4.setText("   TRABAJOS");
        jMenu4.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(110, 19));

        jMenu14.setForeground(new java.awt.Color(0, 51, 255));
        jMenu14.setText("TRABAJOS");
        jMenu14.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N

        jMenuItem25.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem25.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem25.setText("TRABAJO NUEVO");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem25);

        jMenuItem35.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem35.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem35.setText("CREAR LOTES DE TRABAJOS");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem35);

        jMenuItem32.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem32.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem32.setText("ENTREGA DE LOTES DE TRABAJOS");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem32);

        jMenuItem27.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem27.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem27.setText("ENTREGA DE MATERIALES POR TRABAJO");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem27);

        jMenuItem33.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem33.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem33.setText("EDITAR NOTAS Y CANTIDAD DE LOTES");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem33);

        jMenuItem36.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem36.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem36.setText("EDITAR CANTIDAD EN TRABAJOS");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem36);

        jMenuItem37.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem37.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem37.setText("CONSULTA TRABAJOS ENTREGADOS");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem37);

        jMenu4.add(jMenu14);

        jMenu15.setForeground(new java.awt.Color(0, 51, 255));
        jMenu15.setText("MATERIALES");
        jMenu15.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N

        jMenuItem26.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem26.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem26.setText("AGREGAR MATERIALES A P/N");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem26);

        jMenuItem30.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem30.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem30.setText("CONSULTA P/N UTILIZADO POR MATERIAL");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem30);

        jMenuItem28.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem28.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem28.setText("CONSULTA DE MATERIAL ENTREGADO");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem28);

        jMenuItem29.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem29.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem29.setText("CONSULTA MATERIAL DESCARGADO");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem29);

        jMenu4.add(jMenu15);

        menubar.add(jMenu4);

        DWN.setForeground(new java.awt.Color(0, 51, 255));
        DWN.setText("  DRAWINGS");
        DWN.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        DWN.setPreferredSize(new java.awt.Dimension(110, 19));
        DWN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DWNActionPerformed(evt);
            }
        });

        jMenuItem19.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem19.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem19.setText("P/N");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        DWN.add(jMenuItem19);

        jMenuItem22.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem22.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem22.setText("Fotos y Drawings");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        DWN.add(jMenuItem22);

        menubar.add(DWN);

        jMenu5.setForeground(new java.awt.Color(0, 51, 255));
        jMenu5.setText("       SALIR");
        jMenu5.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(110, 19));
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem5.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jMenuItem5.setText("SALIR");
        jMenuItem5.setPreferredSize(new java.awt.Dimension(85, 35));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        menubar.add(jMenu5);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void avencer(){
       
        
        try {
            Connection con = BD.getConnection();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select count(fecha_ven) from Ingreso where ingreso.fecha_ven between to_date(sysdate,'dd/mm/yy') and to_date(sysdate+30,'dd/mm/yy') and estado = 'A'");
            rs.next();
            int codigo = rs.getInt("count(fecha_ven)");
            if (codigo > 0) {

                Vencimieto M = new Vencimieto();
                jDesktopPane1.add(M);
                Dimension desktopSize = jDesktopPane1.getSize();
                Dimension FrameSize = M.getSize();
                M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
                M.show();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR CONTACTE AL ADMINISTRADOR DEL SISTEMA" + e);
        }
    }

    
    private void NUEVOPROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVOPROActionPerformed
        MProducto pro = new MProducto();
        jDesktopPane1.add(pro); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = pro.getSize();
        pro.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        pro.show();

    }//GEN-LAST:event_NUEVOPROActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        salir();    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void familiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familiasActionPerformed
        
         MIngresoFamilia f = new MIngresoFamilia();
        jDesktopPane1.add(f); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = f.getSize();
        f.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        f.show();
        
        
        
    }//GEN-LAST:event_familiasActionPerformed

    private void EDITARPROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITARPROActionPerformed
        EditProducto EP = new EditProducto();
        jDesktopPane1.add(EP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = EP.getSize();
        EP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        EP.show();
    }//GEN-LAST:event_EDITARPROActionPerformed

    private void DESCARGAPROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DESCARGAPROActionPerformed
        DescargaProducto DP = new DescargaProducto();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
    }//GEN-LAST:event_DESCARGAPROActionPerformed

    private void CARGAPROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARGAPROActionPerformed
        CargarProductos CP = new CargarProductos();
        jDesktopPane1.add(CP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = CP.getSize();
        CP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        CP.show();
    }//GEN-LAST:event_CARGAPROActionPerformed

    private void CONSULTAPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTAPNActionPerformed

        CDescargaPN M = new CDescargaPN();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();




    }//GEN-LAST:event_CONSULTAPNActionPerformed

    private void unidadmedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadmedidaActionPerformed
                 
         MUnidad_Medida M = new MUnidad_Medida();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_unidadmedidaActionPerformed

    private void presentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentacionActionPerformed

         MPresentacion P = new MPresentacion();
        jDesktopPane1.add(P); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = P.getSize();
        P.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        P.show();


    }//GEN-LAST:event_presentacionActionPerformed

    private void PROCEDENCIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROCEDENCIAActionPerformed
        
         MProcedencia M = new MProcedencia();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
        
        
        
    }//GEN-LAST:event_PROCEDENCIAActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
                   
         Cproducto CP = new Cproducto();
        jDesktopPane1.add(CP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = CP.getSize();
        CP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        CP.show();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        CDescargaFecha M = new CDescargaFecha();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        CIngresoFecha M = new CIngresoFecha();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
         
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CodigoFoto M = new CodigoFoto();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CIngresoRangoFecha M = new CIngresoRangoFecha();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
      
        CIngresoCodigo M = new CIngresoCodigo();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        
        CIngresoPN M = new CIngresoPN();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void INGRESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESOActionPerformed
       
        EditarIngresos M = new EditarIngresos();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
        
        
    }//GEN-LAST:event_INGRESOActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
      
        CIngresoInvoice M = new CIngresoInvoice();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       
        CDescargasCodigo M = new CDescargasCodigo();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        CDescargasRangoFecha M = new CDescargasRangoFecha();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        
        matporvencer M = new matporvencer();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        matvencidos M = new matvencidos();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        CIngresoNombre M = new CIngresoNombre();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
       Agotados1 M = new Agotados1();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        CDescargasCodigo1 M = new CDescargasCodigo1();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed

        CIngresoCodigo1 M = new CIngresoCodigo1();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();

    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void DWNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DWNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DWNActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        Drawings M = new Drawings();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        Fotos M = new Fotos();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        
        CListaProductoNombre M = new CListaProductoNombre();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        ProductoNombre M = new ProductoNombre();
        jDesktopPane1.add(M); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = M.getSize();
        M.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        M.show();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
       
        TRABAJOS DP = new TRABAJOS();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
        
        
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
       
        MaterialesTrabajos DP = new MaterialesTrabajos();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
        
        
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
      
        ENTREGAS DP = new ENTREGAS();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
        
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        
        CONSULTAENTREGAS DP = new CONSULTAENTREGAS();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
       
        CONSULTAENTREGASDESCARGAS DP = new CONSULTAENTREGASDESCARGAS();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void CARGAPRO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARGAPRO1ActionPerformed
        
        CargarProductosContablesKardex2 DP = new CargarProductosContablesKardex2();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
        
        
        
    }//GEN-LAST:event_CARGAPRO1ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        PNUtilizadoEnProducto DP = new PNUtilizadoEnProducto();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        ReporteBodega DP = new ReporteBodega();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        EntregaTrabajo DP = new EntregaTrabajo();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        EditarNotaTrabajos DP = new EditarNotaTrabajos();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        
        ReportesDetalladosMES DP = new ReportesDetalladosMES();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
        
        
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        TRABAJOS2 DP = new TRABAJOS2();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
        
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
       
        EDITTRABAJOS DP = new EDITTRABAJOS();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
        
        
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        ReportesDetalladosKardex2 DP = new ReportesDetalladosKardex2();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        TrabajosEntregados DP = new TrabajosEntregados();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        CIngresoPO DP = new CIngresoPO();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       
        CIngresoJOB DP = new CIngresoJOB();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
         CDescargasPO DP = new CDescargasPO();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
        CDescargasJOB DP = new CDescargasJOB();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        UpdateCantidadMinima DP = new UpdateCantidadMinima();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        ReporteCostos DP = new ReporteCostos();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
        
        ConsultaKardex DP = new ConsultaKardex();
        jDesktopPane1.add(DP); 
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = DP.getSize();
        DP.setLocation((desktopSize.width - FrameSize.width)/2 , (desktopSize.height - FrameSize.height)/2);
        DP.show();
        
        
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CARGAPRO;
    private javax.swing.JMenuItem CARGAPRO1;
    private javax.swing.JMenuItem CONSULTAPN;
    private javax.swing.JMenuItem DESCARGAPRO;
    private javax.swing.JMenu DWN;
    private javax.swing.JMenuItem EDITARPRO;
    private javax.swing.JMenuItem INGRESO;
    private javax.swing.JMenuItem NUEVOPRO;
    private javax.swing.JMenuItem PROCEDENCIA;
    private javax.swing.JMenu Vencimientos;
    private javax.swing.JMenuItem familias;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private Formularios.MProcedencia mProcedencia1;
    private Formularios.MProcedencia mProcedencia2;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem presentacion;
    private javax.swing.JMenuItem unidadmedida;
    // End of variables declaration//GEN-END:variables

    private void salir() {

        System.exit(1);
    }
}
